/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.testforshoestore;

/**
 *
 * @author Administrator
 */
public class MainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Main = new javax.swing.JPanel();
        jScrollBar1 = new javax.swing.JScrollBar();
        jTextField1 = new javax.swing.JTextField();
        Filter = new javax.swing.JPanel();
        NewB1 = new javax.swing.JButton();
        NewB2 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        NewB3 = new javax.swing.JButton();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        NewB4 = new javax.swing.JButton();
        jCheckBox16 = new javax.swing.JCheckBox();
        jCheckBox17 = new javax.swing.JCheckBox();
        jCheckBox18 = new javax.swing.JCheckBox();
        jCheckBox19 = new javax.swing.JCheckBox();
        jCheckBox20 = new javax.swing.JCheckBox();
        Menu = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        NewB = new javax.swing.JButton();
        MenB = new javax.swing.JButton();
        WomenB = new javax.swing.JButton();
        SpecialB = new javax.swing.JButton();
        SearchF = new javax.swing.JTextField();
        SearchB = new javax.swing.JButton();
        FavB = new javax.swing.JButton();
        CartB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        Main.setBackground(new java.awt.Color(255, 255, 255));

        jScrollBar1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollBar1.setBlockIncrement(5);

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(0, 0, 0));
        jTextField1.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("New");
        jTextField1.setFocusable(false);
        jTextField1.setRequestFocusEnabled(false);
        jTextField1.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout MainLayout = new javax.swing.GroupLayout(Main);
        Main.setLayout(MainLayout);
        MainLayout.setHorizontalGroup(
            MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        MainLayout.setVerticalGroup(
            MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(MainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Filter.setBackground(new java.awt.Color(249, 249, 249));

        NewB1.setBackground(new java.awt.Color(249, 249, 249));
        NewB1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        NewB1.setText("Filter");
        NewB1.setBorder(null);
        NewB1.setBorderPainted(false);
        NewB1.setContentAreaFilled(false);
        NewB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewB1ActionPerformed(evt);
            }
        });

        NewB2.setBackground(new java.awt.Color(249, 249, 249));
        NewB2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        NewB2.setText("Brand");
        NewB2.setBorder(null);
        NewB2.setBorderPainted(false);
        NewB2.setContentAreaFilled(false);
        NewB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewB2ActionPerformed(evt);
            }
        });

        jCheckBox1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckBox1.setText("Adidas");

        jCheckBox2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckBox2.setText("ASUCS");

        jCheckBox3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckBox3.setText("New Balance");

        jCheckBox4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckBox4.setText("Nike");

        jCheckBox5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckBox5.setText("Puma");

        NewB3.setBackground(new java.awt.Color(249, 249, 249));
        NewB3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        NewB3.setText("Size");
        NewB3.setBorder(null);
        NewB3.setBorderPainted(false);
        NewB3.setContentAreaFilled(false);
        NewB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewB3ActionPerformed(evt);
            }
        });

        jCheckBox6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckBox6.setText("36");

        jCheckBox7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckBox7.setText("41");

        jCheckBox8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckBox8.setText("37");

        jCheckBox9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckBox9.setText("38");

        jCheckBox10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckBox10.setText("39");

        jCheckBox11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckBox11.setText("40");

        jCheckBox12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckBox12.setText("42");

        jCheckBox13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckBox13.setText("44");

        jCheckBox14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckBox14.setText("43");
        jCheckBox14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox14ActionPerformed(evt);
            }
        });

        jCheckBox15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckBox15.setText("45");

        NewB4.setBackground(new java.awt.Color(249, 249, 249));
        NewB4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        NewB4.setText("Price");
        NewB4.setBorder(null);
        NewB4.setBorderPainted(false);
        NewB4.setContentAreaFilled(false);
        NewB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewB4ActionPerformed(evt);
            }
        });

        jCheckBox16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckBox16.setText("1,000 - 1,999 ฿");

        jCheckBox17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckBox17.setText("2,000 - 2,999 ฿");

        jCheckBox18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckBox18.setText("3,000 - 3,999 ฿");

        jCheckBox19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckBox19.setText("4,000 - 4,999 ฿");

        jCheckBox20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckBox20.setText("5,000 - 5,999 ฿");

        javax.swing.GroupLayout FilterLayout = new javax.swing.GroupLayout(Filter);
        Filter.setLayout(FilterLayout);
        FilterLayout.setHorizontalGroup(
            FilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FilterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NewB1)
                    .addComponent(NewB2)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox3)
                    .addComponent(jCheckBox4)
                    .addComponent(jCheckBox5)
                    .addComponent(NewB3)
                    .addGroup(FilterLayout.createSequentialGroup()
                        .addGroup(FilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox6)
                            .addComponent(jCheckBox8)
                            .addComponent(jCheckBox9)
                            .addComponent(jCheckBox10)
                            .addComponent(jCheckBox11))
                        .addGap(51, 51, 51)
                        .addGroup(FilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox15)
                            .addComponent(jCheckBox13)
                            .addComponent(jCheckBox12)
                            .addComponent(jCheckBox7)
                            .addComponent(jCheckBox14)))
                    .addComponent(NewB4)
                    .addComponent(jCheckBox16)
                    .addComponent(jCheckBox17)
                    .addComponent(jCheckBox18)
                    .addComponent(jCheckBox19)
                    .addComponent(jCheckBox20))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        FilterLayout.setVerticalGroup(
            FilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FilterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NewB1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NewB2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NewB3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox6)
                    .addComponent(jCheckBox7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox8)
                    .addComponent(jCheckBox12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox9)
                    .addComponent(jCheckBox14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox10)
                    .addComponent(jCheckBox13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FilterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox11)
                    .addComponent(jCheckBox15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NewB4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox20)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        Menu.setBackground(new java.awt.Color(249, 249, 249));

        Title.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("Nutthapong");

        NewB.setBackground(new java.awt.Color(249, 249, 249));
        NewB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NewB.setText("New");
        NewB.setBorder(null);
        NewB.setBorderPainted(false);
        NewB.setContentAreaFilled(false);

        MenB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MenB.setText("Men");
        MenB.setBorder(null);
        MenB.setBorderPainted(false);
        MenB.setContentAreaFilled(false);
        MenB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenBActionPerformed(evt);
            }
        });

        WomenB.setBackground(new java.awt.Color(204, 204, 204));
        WomenB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        WomenB.setText("Women");
        WomenB.setBorder(null);
        WomenB.setContentAreaFilled(false);
        WomenB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WomenBActionPerformed(evt);
            }
        });

        SpecialB.setBackground(new java.awt.Color(204, 204, 204));
        SpecialB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SpecialB.setText("Special Deal");
        SpecialB.setBorder(null);
        SpecialB.setContentAreaFilled(false);
        SpecialB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SpecialBActionPerformed(evt);
            }
        });

        SearchF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SearchF.setToolTipText("");
        SearchF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        SearchF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchFActionPerformed(evt);
            }
        });

        SearchB.setText("🔎");

        FavB.setBackground(new java.awt.Color(204, 204, 204));
        FavB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        FavB.setText("favorite");
        FavB.setBorder(null);
        FavB.setContentAreaFilled(false);
        FavB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FavBActionPerformed(evt);
            }
        });

        CartB.setBackground(new java.awt.Color(204, 204, 204));
        CartB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CartB.setText("Cart");
        CartB.setBorder(null);
        CartB.setContentAreaFilled(false);
        CartB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CartBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(NewB)
                .addGap(26, 26, 26)
                .addComponent(MenB)
                .addGap(18, 18, 18)
                .addComponent(WomenB)
                .addGap(18, 18, 18)
                .addComponent(SpecialB)
                .addGap(28, 28, 28)
                .addComponent(SearchF, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SearchB, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(FavB)
                .addGap(18, 18, 18)
                .addComponent(CartB)
                .addGap(35, 35, 35))
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NewB)
                    .addComponent(MenB)
                    .addComponent(WomenB)
                    .addComponent(SpecialB)
                    .addComponent(SearchF, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchB, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FavB)
                    .addComponent(CartB)
                    .addComponent(Title))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Filter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Filter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenBActionPerformed

    private void WomenBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WomenBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WomenBActionPerformed

    private void SpecialBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SpecialBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SpecialBActionPerformed

    private void SearchFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchFActionPerformed

    private void FavBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FavBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FavBActionPerformed

    private void CartBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CartBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CartBActionPerformed

    private void NewB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewB1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewB1ActionPerformed

    private void NewB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewB2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewB2ActionPerformed

    private void NewB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewB3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewB3ActionPerformed

    private void jCheckBox14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox14ActionPerformed

    private void NewB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewB4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewB4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CartB;
    private javax.swing.JButton FavB;
    private javax.swing.JPanel Filter;
    private javax.swing.JPanel Main;
    private javax.swing.JButton MenB;
    private javax.swing.JPanel Menu;
    private javax.swing.JButton NewB;
    private javax.swing.JButton NewB1;
    private javax.swing.JButton NewB2;
    private javax.swing.JButton NewB3;
    private javax.swing.JButton NewB4;
    private javax.swing.JButton SearchB;
    private javax.swing.JTextField SearchF;
    private javax.swing.JButton SpecialB;
    private javax.swing.JLabel Title;
    private javax.swing.JButton WomenB;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox19;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox20;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
